name: sjd
favicon: null
layout_spectrum: 0.5829174041282386
typography_spectrum: 0.17312764609232545
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.27973568509332836
  lightness: 0.9183283280581236
  saturation: 0.5050969666335732
  rhythmicContrast: 0.8953154743649065
purpose: []
